const menu = [
  {
    id: 1,
    shirtName: "bella canvas",
    color: "blue",
    orderId: 1774837,
    category: "elite",
    size: "XL",
    quantiy: 2,
    date: "10 - 6 - 2020",
    price: 15.99,
    img: "./svg/orangeShirt.png",
  },
  {
    id: 2,
    shirtName: "original fav",
    color: "darkblue",
    orderId: 1774852,
    category: "premium",
    size: "XXL",
    quantiy: 1,
    date: "10 - 6 - 2020",
    price: 19.99,
    img: "./svg/pinkShirt.png",
  },
  {
    id: 3,
    shirtName: "anvil tee",
    color: "palegreen",
    orderId: 1730837,
    category: "basic",
    size: "L",
    quantiy: 1,
    date: "7 - 3 - 2020",
    price: 12.99,
    img: "./svg/greenShirt.png",
  },
  {
    id: 4,
    shirtName: "bela ciao",
    color: "hotpink",
    orderId: 1771637,
    category: "platinum",
    size: "sm",
    quantiy: 5,
    date: "30 - 2 - 2020",
    price: 15.99,
    img: "./svg/orangeShirt.png",
  },
  {
    id: 5,
    shirtName: "bela ciao",
    color: "red",
    orderId: 1771637,
    category: "platinum",
    size: "sm",
    quantiy: 5,
    date: "30 - 2 - 2020",
    price: 15.99,
    img: "./svg/greenShirt.png",
  },
  {
    id: 6,
    shirtName: "bela ciao",
    color: "yellow",
    orderId: 1771637,
    category: "platinum",
    size: "sm",
    quantiy: 5,
    date: "30 - 2 - 2020",
    price: 15.99,
    img: "./svg/pinkShirt.png",
  },
];
export default menu;
